import{a as L,i as n,S as b}from"./assets/vendor-09d7c26e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const P=100;let h=0;const m=(o,r=1)=>{const e=`https://pixabay.com/api/?key=42410938-e2284def214256f6c05887d1a&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${P}`;return L.get(e).then(t=>{const c=t.data.totalHits;return h+=t.data.hits.length,h>=c?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):t.data.hits}).catch(t=>{console.log(t)})};let d;function g(o,r){const a=o.map(s=>`
      <li class="gallery-item">
        <a href="${s.largeImageURL}" class="gallery-link">
          <img src="${s.webformatURL}" alt="${s.tags}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${s.likes}</p>
          <p class="info-item"><b>Views</b> ${s.views}</p>
          <p class="info-item"><b>Comments</b> ${s.comments}</p>
          <p class="info-item"><b>Downloads</b> ${s.downloads}</p>
        </div>
      </li>
      `).join("");r.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new b(".gallery a",{captions:!0,captionsData:"alt",captionsDelay:200})}const y=document.querySelector(".search-form"),u=document.querySelector(".gallery"),l=document.querySelector(".preloader"),i=document.querySelector(".load-more-button");i.classList.add("hidden");let p="",f=1;y.addEventListener("submit",async o=>{o.preventDefault(),l.style.display="flex";const r=y.elements.searchQuery.value.trim();if(!r){n.error({message:"Please, fill the input",position:"topRight"}),l.style.display="none";return}r!==p&&(p=r,f=1,u.innerHTML="",i.classList.add("hidden"));try{const a=await m(r);if(g(a,u),a.length===0){i.classList.add("hidden"),n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}else i.classList.remove("hidden")}catch{n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{l.style.display="none"}});i.addEventListener("click",async()=>{i.classList.add("hidden"),f+=1,l.style.display="flex",l.style.alignItems="flex-end";try{const o=await m(p,f);g(o,u),o.length===0?(i.classList.add("hidden"),n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})):i.classList.remove("hidden")}catch{n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{l.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
